version: '3.4'
volumes:
  bundles:
  pg-data:
services:
  app:
    build: .
    command: rails server -p 3000 -b 0.0.0.0
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@postgres-9.6/dev
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundles:/usr/local/bundle

  db:
    container_name: postgres-9.6
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - pg-data:/var/lib/postgresql/data
