version: '3'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - postgres
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres:///root
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  postgres:
    container_name: postgres-9.6
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
    ports:
      - "5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

